# Generated by Django 5.2.6 on 2025-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(default='', max_length=360),
        ),
    ]
